# Generated by Django 6.0 on 2026-01-09 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Atividade')),
                ('tipo', models.CharField(choices=[('quiz', 'Quiz'), ('desafio', 'Desafio'), ('video', 'Vídeo Interativo')], default='quiz', max_length=20)),
                ('pontuacao', models.IntegerField(default=0, verbose_name='Pontuação')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='disciplinas.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
    ]
