# Generated by Django 6.0 on 2026-01-10 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='pontuacao',
        ),
        migrations.AddField(
            model_name='atividade',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='materiais/', verbose_name='Arquivo PDF/Material'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Instruções ou Resumo'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='link_video',
            field=models.URLField(blank=True, null=True, verbose_name='Link de Vídeo Aula (YouTube)'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='disciplinas.disciplina'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='tipo',
            field=models.CharField(choices=[('material', 'Material de Estudo (PDF/Link)'), ('quiz', 'Quiz Interativo')], default='material', max_length=20),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('opcao_a', models.CharField(max_length=255)),
                ('opcao_b', models.CharField(max_length=255)),
                ('opcao_c', models.CharField(max_length=255)),
                ('opcao_d', models.CharField(max_length=255)),
                ('resposta_correta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='atividades.atividade')),
            ],
        ),
    ]
