# Generated by Django 6.0 on 2026-01-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='professores/')),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Professores',
            },
        ),
    ]
