# Generated by Django 6.0 on 2026-02-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
