# Generated by Django 6.0 on 2026-02-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0002_professor_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='ano_graduacao',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='professor',
            name='area',
            field=models.CharField(default='Não informado', max_length=100),
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(default='sememail@exemplo.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='escola',
            field=models.CharField(default='Não informado', max_length=150),
        ),
    ]
